### ISSUE TITLE
move mininet/FRR/pythondev setup from update scripts to provisioning scripts

### ISSUE THREAD

**Issue by StefanoSalsano** [netgroup/rose-vm#8]
we need to change (at least):

- https://github.com/netgroup/rose-vm/blob/master/scripts/update_all.sh

- https://github.com/netgroup/rose-vm-build/blob/master/packer/execute-xubuntu-vagrant-vbox-from-box.sh

remove the following (or better move them in rose-vm-build):
- https://github.com/netgroup/rose-vm/blob/master/scripts/setup_frr.sh
- https://github.com/netgroup/rose-vm/blob/master/scripts/build_deploy_docker_stack.sh
- https://github.com/netgroup/rose-vm/blob/master/scripts/build_proto.sh
- https://github.com/netgroup/rose-vm/blob/master/scripts/setup_python_dep.sh

**Comment by cscarpitta** [comment]
- https://github.com/netgroup/rose-vm/blob/master/scripts/setup_frr.sh moved to rose-vm-build
- https://github.com/netgroup/rose-vm/blob/master/scripts/build_deploy_docker_stack.sh leaved in rose-vm
- https://github.com/netgroup/rose-vm/blob/master/scripts/build_proto.sh no longer required
- https://github.com/netgroup/rose-vm/blob/master/scripts/setup_python_dep.sh have been splitted in setup_controller.sh, setup_node_mgr.sh and setup_srv6_tutorial.sh
